dev501.102102/src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Address_Error__c</fullName>
        <label>Address Error</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address_2__c</fullName>
        <label>Street Address 2</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valid_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

dev501.102102/src/objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Trace__c</fullName>
        <label>Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dev501.102102/src/classes/ValidateAddresses.cls
public class ValidateAddresses {
    public static Boolean AsyncValidationFlag = false;
    
    @Future(callout=true) 
    public static void validateAddressSOAP(Set<ID> ids) {
        try {
            // 検証対象の住所リストを取得
            Map<ID, Candidate__c> mapCands = findCandidates(ids);
            List<validateAddressSOAP.addressSOAP> listAddress = new List<validateAddressSOAP.addressSOAP>();
            for (Candidate__c cand : mapCands.values()) {
                validateAddressSOAP.addressSOAP address = new validateAddressSOAP.addressSOAP();
                address.id = cand.id;
                address.line1 = cand.Street_Address_1__c;
                address.line2 = cand.Street_Address_2__c;
                address.city = cand.city__c;
                address.state = cand.state_Province__c;
                address.country = cand.country__c;
                address.zipCode = cand.zip_postal_code__c;
                listAddress.add(address);
            }
                        
            // TODO: ValidateAddressSOAP.ValidateAddressesPort型の変数portを宣言、デフォルトコンストラクタを使用してインスタンスを代入
			ValidateAddressSOAP.ValidateAddressesPort port = new ValidateAddressSOAP.ValidateAddressesPort();
            
			// TODO: ValidateAddressSOAP.validationResultSOAP型の変数listResultを宣言
			List<ValidateAddressSOAP.validationResultSOAP> listResult;

			// TODO: port変数のValidateAddressesメソッドを呼び出し、実行結果を上記変数に代入する。引数にはlistAddressを渡す
			listResult = port.ValidateAddresses(listAddress);

            // 結果の検証
            for (ValidateAddressSOAP.validationResultSOAP result : listResult) {
                Candidate__c cand = mapCands.get(result.testAddress.id);
                if (result.isValid) {
                    cand.Valid_Address__c = true;
                    cand.Address_Error__c = null;
                } else {
                    cand.Valid_Address__c = false;
                    cand.Address_Error__c = '住所不正';
                }
            }
            
            // Candidateの更新
            AsyncValidationFlag = true;
            update mapCands.values();
        } catch (Exception ex) {
            // 例外処理
            System.debug('ERROR: '+ ex);
            Error_Log__c log = new Error_Log__c();
            log.trace__c = ex.getCause() + '\n' + ex.getMessage();
            insert log;        
        }
    }
       
    private static Map<ID, Candidate__c> findCandidates(Set<ID> ids) {
        Map<ID, Candidate__c> output;
        output = new Map<ID, Candidate__c>([SELECT ID, Street_Address_1__c, Street_Address_2__c, city__c,
                                                state_Province__c, country__c, zip_postal_code__c
                                            FROM candidate__c
                                            WHERE id in :ids]);
        return output;
    }
}